# Generated by Django 5.2.8 on 2025-11-30 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('lead_id', models.IntegerField(blank=True, null=True)),
                ('event', models.TextField()),
                ('details', models.TextField(blank=True, null=True)),
                ('created_at', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'audit_log',
                'ordering': ['-id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FormResponse',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('lead_id', models.IntegerField(blank=True, null=True)),
                ('visa_country', models.TextField(blank=True, null=True)),
                ('form_id', models.TextField(blank=True, null=True)),
                ('response_id', models.TextField(unique=True)),
                ('respondent_email', models.TextField(blank=True, null=True)),
                ('raw_json', models.TextField(blank=True, null=True)),
                ('created_at', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'form_responses',
                'ordering': ['-id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('message_id', models.TextField()),
                ('conversation_id', models.TextField(blank=True, null=True)),
                ('from_address', models.TextField(blank=True, null=True)),
                ('subject', models.TextField(blank=True, null=True)),
                ('status', models.TextField()),
                ('visa_country', models.TextField(blank=True, null=True)),
                ('questionnaire_status', models.TextField(default='none')),
                ('questionnaire_form_id', models.TextField(blank=True, null=True)),
                ('questionnaire_response_id', models.TextField(blank=True, null=True)),
                ('last_message_id', models.TextField(blank=True, null=True)),
                ('last_contacted', models.TextField(blank=True, null=True)),
                ('next_reminder_at', models.TextField(blank=True, null=True)),
                ('reminders_sent', models.IntegerField(default=0)),
                ('form_ack_sent', models.IntegerField(default=0)),
                ('created_at', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'leads',
                'ordering': ['-id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LeadForm',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('lead_id', models.IntegerField(blank=True, null=True)),
                ('form_type', models.TextField(blank=True, null=True)),
                ('raw_text', models.TextField(blank=True, null=True)),
                ('created_at', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'lead_forms',
                'ordering': ['-id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BotSettings',
            fields=[
                ('id', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('bot_name', models.CharField(default='BCD Travel Bot', max_length=100)),
                ('sender_email', models.CharField(default='visa@itplus.kz', max_length=255)),
                ('first_reminder_days', models.IntegerField(default=1)),
                ('second_reminder_days', models.IntegerField(default=3)),
                ('auto_create_leads', models.BooleanField(default=True)),
                ('auto_change_status', models.BooleanField(default=True)),
                ('auto_reminders_enabled', models.BooleanField(default=True)),
                ('form_poland_url', models.CharField(blank=True, max_length=500, null=True)),
                ('form_schengen_url', models.CharField(blank=True, max_length=500, null=True)),
                ('form_usa_url', models.CharField(blank=True, max_length=500, null=True)),
                ('form_generic_url', models.CharField(blank=True, max_length=500, null=True)),
                ('extra_config', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'bot_settings',
                'managed': True,
            },
        ),
    ]
