# Generated by Django 5.2.8 on 2025-12-15 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='botsettings',
            name='poll_interval_seconds',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='botsettings',
            name='send_window_end_hour',
            field=models.IntegerField(default=21),
        ),
        migrations.AddField(
            model_name='botsettings',
            name='send_window_start_hour',
            field=models.IntegerField(default=9),
        ),
    ]
