"""
╔══════════════════════════════════════════════════════════════════════════════╗
║   🤖 AI VISA ASSISTANT v3.1 — BCD TRAVEL Kazakhstan                         ║
║   Интеллектуальный AI-агент для обработки визовых заявок                    ║
║   © 2024-2025 BCD TRAVEL Kazakhstan. All Rights Reserved.                   ║
╚══════════════════════════════════════════════════════════════════════════════╝
"""

from __future__ import annotations
from dataclasses import dataclass, field
from typing import List, Optional, Dict, Any, Union, Tuple, Set
from enum import Enum
import os, logging, json, re
from datetime import datetime

try:
    from openai_client import generate_chat_completion
except ImportError:
    def generate_chat_completion(messages, model="gpt-4o", max_tokens=500, temperature=0.2):
        raise NotImplementedError("OpenAI client not found")

logger = logging.getLogger(__name__)


# ═══════════════════════════════════════════════════════════════════════════════
# 🎨 AI БРЕНДИНГ
# ═══════════════════════════════════════════════════════════════════════════════

@dataclass(frozen=True)
class AIBranding:
    agent_name: str = "AI Visa Assistant"
    agent_version: str = "3.1"
    company_name: str = "BCD TRAVEL Kazakhstan"
    robot_emoji: str = "🤖"
    sparkle_emoji: str = "✨"
    check_emoji: str = "✅"
    arrow_emoji: str = "➤"
    star_emoji: str = "⭐"
    info_emoji: str = "ℹ️"
    warning_emoji: str = "⚠️"
    link_emoji: str = "🔗"
    form_emoji: str = "📋"
    urgent_emoji: str = "🚨"
    line_thin: str = "─" * 50
    
    def get_footer_ru(self) -> str:
        return f"\n{self.line_thin}\n{self.robot_emoji} Это сообщение сформировано {self.agent_name} v{self.agent_version}\n{self.sparkle_emoji} Интеллектуальная система обработки визовых заявок\n\nС уважением,\n{self.company_name}\n{self.star_emoji} visa@bcdtravel.kz\n"
    
    def get_footer_en(self) -> str:
        return f"\n{self.line_thin}\n{self.robot_emoji} This message was generated by {self.agent_name} v{self.agent_version}\n{self.sparkle_emoji} Intelligent Visa Processing System\n\nBest regards,\n{self.company_name}\n{self.star_emoji} visa@bcdtravel.kz\n"

AI_BRAND = AIBranding()


# ═══════════════════════════════════════════════════════════════════════════════
# ⚙️ КОНФИГУРАЦИЯ
# ═══════════════════════════════════════════════════════════════════════════════

@dataclass(frozen=True)
class Config:
    mailbox_upn: str = field(default_factory=lambda: os.getenv("MAILBOX_UPN", "RobotVisa@itplus.kz"))
    non_standard_forward_email: str = field(default_factory=lambda: os.getenv("NON_STANDARD_FORWARD_EMAIL", "specialists@bcdtravel.kz"))
    default_model: str = field(default_factory=lambda: os.getenv("OPENAI_MODEL", "gpt-4o"))
    max_tokens_reply: int = 1000
    temperature: float = 0.25
    
    # URL Анкет
    questionnaire_poland_url: Optional[str] = field(default_factory=lambda: os.getenv("QUESTIONNAIRE_POLAND_URL") or os.getenv("FORM_POLAND_URL"))
    questionnaire_schengen_url: Optional[str] = field(default_factory=lambda: os.getenv("QUESTIONNAIRE_SCHENGEN_URL") or os.getenv("FORM_SCHENGEN_URL"))
    questionnaire_usa_url: Optional[str] = field(default_factory=lambda: os.getenv("QUESTIONNAIRE_USA_URL") or os.getenv("FORM_USA_URL"))
    questionnaire_generic_url: Optional[str] = field(default_factory=lambda: os.getenv("QUESTIONNAIRE_GENERIC_URL") or os.getenv("FORM_GENERIC_URL"))
    
    # ID полей в Google Forms для pre-filled link (entry.XXXXXX)
    entry_id_poland: str = field(default_factory=lambda: os.getenv("GF_ENTRY_ID_POLAND", ""))
    entry_id_schengen: str = field(default_factory=lambda: os.getenv("GF_ENTRY_ID_SCHENGEN", ""))
    entry_id_usa: str = field(default_factory=lambda: os.getenv("GF_ENTRY_ID_USA", ""))
    entry_id_generic: str = field(default_factory=lambda: os.getenv("GF_ENTRY_ID_GENERIC", ""))

CONFIG = Config()


# ═══════════════════════════════════════════════════════════════════════════════
# 📊 ПЕРЕЧИСЛЕНИЯ
# ═══════════════════════════════════════════════════════════════════════════════

class Language(Enum):
    RUSSIAN = "ru"
    ENGLISH = "en"
    KAZAKH = "kk"
    @classmethod
    def default(cls): return cls.RUSSIAN

class Intent(Enum):
    WANT_APPLY = "want_apply"
    SEND_DOCS = "send_docs"
    INFO_REQUEST = "info_request"
    FOLLOWUP = "followup"
    COMPLAINT = "complaint"
    GRATITUDE = "gratitude"
    CANCELLATION = "cancellation"
    RESCHEDULE = "reschedule"
    PAYMENT = "payment"
    OTHER = "other"
    @classmethod
    def default(cls): return cls.OTHER

class LeadStatus(Enum):
    NEW = "new"
    INFO_PROVIDED = "info_provided"
    QUESTIONNAIRE_SENT = "questionnaire_sent"
    QUESTIONNAIRE_FILLED = "questionnaire_filled"
    DOCS_IN_PROGRESS = "docs_in_progress"
    DOCS_COLLECTED = "docs_collected"
    SUBMITTED = "submitted"
    APPROVED = "approved"
    REJECTED = "rejected"
    COMPLETED = "completed"
    CANCELLED = "cancelled"
    @classmethod
    def default(cls): return cls.NEW
    @classmethod
    def from_string(cls, s):
        if not s: return cls.default()
        try: return cls(s.lower().strip())
        except: return cls.default()

class UrgencyLevel(Enum):
    CRITICAL = 5
    VERY_HIGH = 4
    HIGH = 3
    MEDIUM = 2
    NORMAL = 1
    LOW = 0
    @property
    def emoji(self):
        return {5: "🔴", 4: "🟠", 3: "🟡", 2: "🟢", 1: "🔵", 0: "⚪"}.get(self.value, "⚪")

class VisaCategory(Enum):
    STANDARD = "standard"
    NON_STANDARD = "non_standard"

class Sentiment(Enum):
    VERY_POSITIVE = "very_positive"
    POSITIVE = "positive"
    NEUTRAL = "neutral"
    NEGATIVE = "negative"
    VERY_NEGATIVE = "very_negative"
    @property
    def emoji(self):
        return {"very_positive": "😄", "positive": "🙂", "neutral": "😐", "negative": "😟", "very_negative": "😠"}.get(self.value, "😐")


# ═══════════════════════════════════════════════════════════════════════════════
# 📦 МОДЕЛИ ДАННЫХ
# ═══════════════════════════════════════════════════════════════════════════════

@dataclass
class Message:
    from_address: str
    subject: str
    body: str
    received_at: Optional[str] = None
    attachments: List[str] = field(default_factory=list)
    
    @property
    def full_text(self):
        parts = []
        if self.subject: parts.append(f"[Тема: {self.subject}]")
        if self.body: parts.append(self.body)
        return "\n".join(parts)
    
    @classmethod
    def from_dict(cls, data):
        from_data = data.get("from", {})
        email_data = from_data.get("emailAddress", {}) if isinstance(from_data, dict) else {}
        body_data = data.get("body", {})
        body_content = body_data.get("content", "") if isinstance(body_data, dict) else str(body_data)
        return cls(
            from_address=email_data.get("address", "") if isinstance(email_data, dict) else "",
            subject=data.get("subject", ""),
            body=data.get("bodyPreview", "") or body_content,
            received_at=data.get("receivedDateTime"),
            attachments=[a.get("name", "") for a in data.get("attachments", []) if isinstance(a, dict)],
        )
    
    def get_clean_body(self):
        text = re.sub(r'<[^>]+>', ' ', self.body)
        text = re.sub(r'\s+', ' ', text)
        return text.strip()

@dataclass
class Country:
    code: str
    names: Set[str]
    category: VisaCategory
    questionnaire_type: Optional[str] = None
    processing_notes: Optional[str] = None

@dataclass
class QuestionnaireLinks:
    poland: Optional[str] = None
    schengen: Optional[str] = None
    usa: Optional[str] = None
    generic: Optional[str] = None
    
    @classmethod
    def from_config(cls):
        return cls(poland=CONFIG.questionnaire_poland_url, schengen=CONFIG.questionnaire_schengen_url,
                   usa=CONFIG.questionnaire_usa_url, generic=CONFIG.questionnaire_generic_url)
    
    def get_personal_link(self, type_code: str, lead_id: Union[int, str, None]) -> Optional[str]:
        """
        Генерирует персональную ссылку с предзаполненным Lead ID.
        """
        base_url = getattr(self, type_code, None)
        if not base_url: return None
        if not lead_id: return base_url

        entry_id = getattr(CONFIG, f"entry_id_{type_code}", "")
        
        if entry_id and "docs.google.com" in base_url:
            separator = "&" if "?" in base_url else "?"
            return f"{base_url}{separator}{entry_id}={lead_id}"
        
        return base_url

@dataclass
class ThreadAnalysis:
    language: Language
    detected_country: Optional[Country]
    intent: Intent
    urgency: UrgencyLevel
    sentiment: Sentiment
    previous_status: LeadStatus
    new_status: LeadStatus
    offer_poland_questionnaire: bool = False
    offer_schengen_questionnaire: bool = False
    offer_usa_questionnaire: bool = False
    offer_generic_questionnaire: bool = False
    is_non_standard_destination: bool = False
    has_attachments: bool = False
    attachment_count: int = 0
    forward_to_email: Optional[str] = None
    forward_reason: Optional[str] = None
    confidence_score: float = 0.0
    analysis_notes: List[str] = field(default_factory=list)
    
    @property
    def country_code(self): return self.detected_country.code if self.detected_country else None
    @property
    def needs_questionnaire(self): return any([self.offer_poland_questionnaire, self.offer_schengen_questionnaire, self.offer_usa_questionnaire, self.offer_generic_questionnaire])
    @property
    def questionnaire_type(self):
        if self.offer_poland_questionnaire: return "poland"
        if self.offer_schengen_questionnaire: return "schengen"
        if self.offer_usa_questionnaire: return "usa"
        if self.offer_generic_questionnaire: return "generic"
        return None
    @property
    def is_urgent(self): return self.urgency in (UrgencyLevel.CRITICAL, UrgencyLevel.VERY_HIGH, UrgencyLevel.HIGH)
    
    def to_dict(self):
        return {
            "language": self.language.value, "country": self.country_code, "intent": self.intent.value,
            "urgency_level": self.urgency.name, "urgency_emoji": self.urgency.emoji,
            "sentiment": self.sentiment.value, "sentiment_emoji": self.sentiment.emoji,
            "previous_status": self.previous_status.value, "new_status": self.new_status.value,
            "offer_poland_questionnaire": self.offer_poland_questionnaire,
            "offer_schengen_questionnaire": self.offer_schengen_questionnaire,
            "offer_usa_questionnaire": self.offer_usa_questionnaire,
            "offer_generic_questionnaire": self.offer_generic_questionnaire,
            "is_urgent": self.is_urgent, "is_non_standard_destination": self.is_non_standard_destination,
            "forward_to_email": self.forward_to_email, "questionnaire_type": self.questionnaire_type,
            "needs_questionnaire": self.needs_questionnaire, "confidence_score": self.confidence_score,
            "has_attachments": self.has_attachments,
            # Обратная совместимость
            "offer_poland_form": self.offer_poland_questionnaire, "offer_schengen_form": self.offer_schengen_questionnaire,
            "offer_usa_form": self.offer_usa_questionnaire, "offer_generic_form": self.offer_generic_questionnaire,
            "needs_form": self.needs_questionnaire, "form_code": self.questionnaire_type,
        }


# ═══════════════════════════════════════════════════════════════════════════════
# 🌍 БАЗА СТРАН
# ═══════════════════════════════════════════════════════════════════════════════

class CountryDatabase:
    SCHENGEN_CODES = frozenset({"AT", "BE", "CZ", "DK", "EE", "FI", "FR", "DE", "GR", "HU", "IS", "IT", "LV", "LI", "LT", "LU", "MT", "NL", "NO", "PL", "PT", "SK", "SI", "ES", "SE", "CH"})
    NON_STANDARD_CODES = frozenset({"GB", "CA", "AU", "NZ", "JP", "CN", "KR", "IN", "BR", "MX", "TR", "AE", "SA", "ZA", "EG", "TH", "VN", "SG", "IL", "MY", "ID"})
    
    def __init__(self):
        self._countries: Dict[str, Country] = {}
        self._keyword_index: Dict[str, str] = {}
        self._build_database()
    
    def _add(self, c): 
        self._countries[c.code] = c
        for n in c.names: self._keyword_index[n.lower()] = c.code
    
    def _build_database(self):
        self._add(Country("PL", {"poland", "польша", "польшу", "warsaw", "варшава", "krakow", "краков", "gdansk", "гданьск"}, VisaCategory.STANDARD, "poland"))
        self._add(Country("US", {"usa", "u.s.", "united states", "america", "америка", "сша", "штаты", "new york", "нью-йорк", "los angeles", "лос-анджелес", "washington", "вашингтон", "miami", "майами", "chicago", "чикаго", "las vegas", "лас-вегас"}, VisaCategory.STANDARD, "usa", "Требуется собеседование"))
        self._add(Country("FR", {"france", "франция", "францию", "paris", "париж", "nice", "ницца", "lyon", "лион", "cannes", "канны"}, VisaCategory.STANDARD, "schengen"))
        self._add(Country("DE", {"germany", "германия", "германию", "berlin", "берлин", "munich", "мюнхен", "frankfurt", "франкфурт", "hamburg", "гамбург"}, VisaCategory.STANDARD, "schengen"))
        self._add(Country("IT", {"italy", "италия", "италию", "rome", "рим", "milan", "милан", "venice", "венеция", "florence", "флоренция"}, VisaCategory.STANDARD, "schengen"))
        self._add(Country("ES", {"spain", "испания", "испанию", "barcelona", "барселона", "madrid", "мадрид", "valencia", "валенсия", "ibiza", "ибица"}, VisaCategory.STANDARD, "schengen"))
        self._add(Country("NL", {"netherlands", "нидерланды", "голландия", "holland", "amsterdam", "амстердам"}, VisaCategory.STANDARD, "schengen"))
        self._add(Country("AT", {"austria", "австрия", "вена", "vienna", "wien", "salzburg", "зальцбург"}, VisaCategory.STANDARD, "schengen"))
        self._add(Country("CZ", {"czech", "czechia", "чехия", "prague", "прага"}, VisaCategory.STANDARD, "schengen"))
        self._add(Country("GR", {"greece", "греция", "грецию", "athens", "афины", "santorini", "санторини", "crete", "крит"}, VisaCategory.STANDARD, "schengen"))
        self._add(Country("CH", {"switzerland", "швейцария", "zurich", "цюрих", "geneva", "женева"}, VisaCategory.STANDARD, "schengen"))
        self._add(Country("PT", {"portugal", "португалия", "lisbon", "лиссабон", "porto", "порту"}, VisaCategory.STANDARD, "schengen"))
        self._add(Country("HU", {"hungary", "венгрия", "budapest", "будапешт"}, VisaCategory.STANDARD, "schengen"))
        self._add(Country("BE", {"belgium", "бельгия", "brussels", "брюссель"}, VisaCategory.STANDARD, "schengen"))
        self._add(Country("SCHENGEN", {"schengen", "шенген", "шенгенскую", "шенгенская", "europe", "европа", "европу", "eu", "евросоюз"}, VisaCategory.STANDARD, "schengen"))
        # Нестандартные
        self._add(Country("GB", {"uk", "united kingdom", "great britain", "england", "британия", "великобритания", "англия", "london", "лондон"}, VisaCategory.NON_STANDARD, None, "⚠️ Требуется британская виза"))
        self._add(Country("CA", {"canada", "канада", "toronto", "торонто", "vancouver", "ванкувер"}, VisaCategory.NON_STANDARD, None, "⚠️ Требуется eTA или виза"))
        self._add(Country("AU", {"australia", "австралия", "sydney", "сидней", "melbourne", "мельбурн"}, VisaCategory.NON_STANDARD, None, "⚠️ Требуется ETA или виза"))
        self._add(Country("JP", {"japan", "япония", "tokyo", "токио", "osaka", "осака"}, VisaCategory.NON_STANDARD, None, "⚠️ Требуется японская виза"))
        self._add(Country("CN", {"china", "китай", "beijing", "пекин", "shanghai", "шанхай"}, VisaCategory.NON_STANDARD, None, "⚠️ Требуется китайская виза"))
        self._add(Country("KR", {"south korea", "korea", "корея", "южная корея", "seoul", "сеул"}, VisaCategory.NON_STANDARD, None, "⚠️ Требуется K-ETA или виза"))
        self._add(Country("TR", {"turkey", "турция", "istanbul", "стамбул", "antalya", "анталия"}, VisaCategory.NON_STANDARD, None, "⚠️ Возможна e-Visa"))
        self._add(Country("AE", {"uae", "emirates", "эмираты", "оаэ", "dubai", "дубай"}, VisaCategory.NON_STANDARD))
        self._add(Country("TH", {"thailand", "таиланд", "тайланд", "bangkok", "бангкок", "phuket", "пхукет"}, VisaCategory.NON_STANDARD, None, "⚠️ Безвиз до 30 дней"))
        self._add(Country("EG", {"egypt", "египет", "cairo", "каир", "sharm", "шарм", "hurghada", "хургада"}, VisaCategory.NON_STANDARD, None, "⚠️ Виза по прибытии"))
    
    def find_country(self, text: str) -> Optional[Country]:
        text_lower = text.lower()
        matches = [(code, len(kw)) for kw, code in self._keyword_index.items() if kw in text_lower]
        if not matches: return None
        matches.sort(key=lambda x: x[1], reverse=True)
        return self._countries.get(matches[0][0])
    
    def is_non_standard(self, code: str) -> bool:
        return code.upper() in self.NON_STANDARD_CODES

COUNTRY_DB = CountryDatabase()


# ═══════════════════════════════════════════════════════════════════════════════
# 🔬 АНАЛИЗАТОРЫ
# ═══════════════════════════════════════════════════════════════════════════════

class TextAnalyzer:
    @staticmethod
    def normalize(text: str, max_len: int = 10000) -> str:
        text = re.sub(r'<[^>]+>', ' ', text)
        text = re.sub(r'\s+', ' ', text)
        return text[-max_len:].strip().lower() if len(text) > max_len else text.strip().lower()

class LanguageDetector(TextAnalyzer):
    MARKERS = {
        Language.ENGLISH: {"strong": ["dear ", "hello", "good afternoon", "please", "thank you", "regards"], "medium": ["the ", "and ", "for ", "with", "from", "have", "will"], "weak": ["is ", "are ", "was "]},
        Language.RUSSIAN: {"strong": ["уважаемый", "здравствуйте", "добрый день", "с уважением", "пожалуйста", "спасибо"], "medium": ["прошу", "необходимо", "требуется", "подскажите", "направляю"], "weak": ["это", "что", "как", "для", "или"]},
        Language.KAZAKH: {"strong": ["сәлем", "сәлеметсіз", "қайырлы", "рахмет"], "medium": ["керек", "болады"], "weak": ["бұл", "мен"]},
    }
    WEIGHTS = {"strong": 3.0, "medium": 1.5, "weak": 0.5}
    
    def detect(self, messages: List[Message]) -> Language:
        text = self.normalize(" ".join(m.full_text for m in messages))
        scores = {lang: sum(text.count(w) * self.WEIGHTS[s] for s, ws in m.items() for w in ws) for lang, m in self.MARKERS.items()}
        best = max(scores, key=lambda k: scores[k])
        if best == Language.KAZAKH and scores[Language.RUSSIAN] > scores[Language.KAZAKH] * 0.5: return Language.RUSSIAN
        return Language.RUSSIAN if scores[best] < 1.0 else best

class IntentDetector(TextAnalyzer):
    PATTERNS = {
        Intent.WANT_APPLY: {"exact": ["хочу подать на визу", "хочу оформить визу", "нужна виза", "оформить визу", "i want to apply", "need a visa"], "combined": [(["виз", "нужн"], 2.5), (["виз", "оформ"], 2.5), (["visa", "apply"], 2.5)]},
        Intent.SEND_DOCS: {"exact": ["направляю документы", "высылаю документы", "во вложении", "attached documents"], "combined": [(["документ", "вложен"], 2.5)]},
        Intent.INFO_REQUEST: {"exact": ["какие документы", "сколько стоит", "какие сроки", "what documents", "how much"], "combined": [(["подскажите", "виз"], 1.5)]},
        Intent.FOLLOWUP: {"exact": ["какой статус", "есть новости", "any update", "status of"], "combined": [(["статус", "виз"], 2.5)]},
        Intent.COMPLAINT: {"exact": ["недоволен", "жалоба", "претензия", "complaint"], "combined": []},
        Intent.GRATITUDE: {"exact": ["спасибо", "благодарю", "thank you"], "combined": []},
        Intent.CANCELLATION: {"exact": ["отменить", "отказываюсь", "cancel"], "combined": [(["отмен", "заявк"], 2.5)]},
        Intent.PAYMENT: {"exact": ["оплата", "счёт", "инвойс", "payment", "invoice"], "combined": []},
    }
    
    def detect(self, messages: List[Message]) -> Tuple[Intent, float]:
        text = self.normalize(" ".join(m.full_text for m in messages))
        scores = {i: sum(3.5 for e in p.get("exact", []) if e in text) + sum(w for kws, w in p.get("combined", []) if all(k in text for k in kws)) for i, p in self.PATTERNS.items()}
        best = max(scores, key=lambda k: scores[k])
        conf = min(scores[best] / 7.0, 1.0)
        return (Intent.OTHER, 0.0) if conf < 0.25 else (best, conf)

class UrgencyDetector(TextAnalyzer):
    MARKERS = {
        UrgencyLevel.CRITICAL: ["вылет сегодня", "вылет завтра", "flight today", "flight tomorrow"],
        UrgencyLevel.HIGH: ["очень срочно", "asap", "urgent", "срочно"],
        UrgencyLevel.MEDIUM: ["как можно скорее", "на этой неделе", "soon"],
    }
    def detect(self, messages: List[Message]) -> UrgencyLevel:
        text = self.normalize(" ".join(m.full_text for m in messages))
        for lvl in [UrgencyLevel.CRITICAL, UrgencyLevel.HIGH, UrgencyLevel.MEDIUM]:
            if any(m in text for m in self.MARKERS.get(lvl, [])): return lvl
        return UrgencyLevel.NORMAL

class SentimentDetector(TextAnalyzer):
    POS = {"спасибо", "благодарю", "отлично", "thank you", "great", "excellent"}
    NEG = {"недоволен", "разочарован", "ужасно", "жалоба", "unhappy", "terrible"}
    def detect(self, messages: List[Message]) -> Sentiment:
        text = self.normalize(" ".join(m.full_text for m in messages))
        p, n = sum(1 for w in self.POS if w in text), sum(1 for w in self.NEG if w in text)
        if n > p: return Sentiment.NEGATIVE
        if p > n and p > 0: return Sentiment.POSITIVE
        return Sentiment.NEUTRAL


# ═══════════════════════════════════════════════════════════════════════════════
# 🔄 МАШИНА СОСТОЯНИЙ И ЛОГИКА
# ═══════════════════════════════════════════════════════════════════════════════

class StatusTransitionEngine:
    TRANSITIONS = {
        LeadStatus.NEW: {Intent.WANT_APPLY: LeadStatus.QUESTIONNAIRE_SENT, Intent.INFO_REQUEST: LeadStatus.INFO_PROVIDED, Intent.SEND_DOCS: LeadStatus.DOCS_IN_PROGRESS},
        LeadStatus.INFO_PROVIDED: {Intent.WANT_APPLY: LeadStatus.QUESTIONNAIRE_SENT, Intent.SEND_DOCS: LeadStatus.DOCS_IN_PROGRESS},
        LeadStatus.QUESTIONNAIRE_SENT: {Intent.SEND_DOCS: LeadStatus.QUESTIONNAIRE_FILLED},
        LeadStatus.QUESTIONNAIRE_FILLED: {Intent.SEND_DOCS: LeadStatus.DOCS_IN_PROGRESS},
        LeadStatus.CANCELLED: {Intent.WANT_APPLY: LeadStatus.QUESTIONNAIRE_SENT},
    }
    @classmethod
    def get_new_status(cls, current, intent): return cls.TRANSITIONS.get(current, {}).get(intent, current)

class QuestionnaireSelector:
    @staticmethod
    def should_offer(country, intent, existing):
        result = {"poland": False, "schengen": False, "usa": False, "generic": False}
        if country and country.category == VisaCategory.NON_STANDARD: return result
        if intent != Intent.WANT_APPLY: return result
        if country and country.questionnaire_type and not existing.get(country.questionnaire_type, False):
            result[country.questionnaire_type] = True
        elif not country and not existing.get("generic", False):
            result["generic"] = True
        return result


# ═══════════════════════════════════════════════════════════════════════════════
# 🔍 ГЛАВНЫЙ АНАЛИЗАТОР
# ═══════════════════════════════════════════════════════════════════════════════

class ThreadAnalyzer:
    def __init__(self):
        self.lang_det, self.intent_det, self.urg_det, self.sent_det = LanguageDetector(), IntentDetector(), UrgencyDetector(), SentimentDetector()
    
    def analyze(self, messages: List[Message], our_address: str = CONFIG.mailbox_upn, previous_status: str = None, existing_questionnaires: Dict[str, bool] = None) -> ThreadAnalysis:
        if not messages: return self._empty(previous_status)
        client_msgs = [m for m in messages if m.from_address.lower() != our_address.lower()] or messages
        
        lang = self.lang_det.detect(client_msgs)
        country = COUNTRY_DB.find_country(" ".join(m.full_text for m in client_msgs))
        intent, conf = self.intent_det.detect(client_msgs)
        urgency = self.urg_det.detect(client_msgs)
        sentiment = self.sent_det.detect(client_msgs)
        
        prev_status = LeadStatus.from_string(previous_status)
        new_status = StatusTransitionEngine.get_new_status(prev_status, intent)
        questionnaires = QuestionnaireSelector.should_offer(country, intent, existing_questionnaires or {})
        
        is_non_std = country and country.category == VisaCategory.NON_STANDARD
        total_att = sum(len(m.attachments) for m in messages)
        
        return ThreadAnalysis(
            language=lang, detected_country=country, intent=intent, urgency=urgency, sentiment=sentiment,
            previous_status=prev_status, new_status=new_status,
            offer_poland_questionnaire=questionnaires["poland"], offer_schengen_questionnaire=questionnaires["schengen"],
            offer_usa_questionnaire=questionnaires["usa"], offer_generic_questionnaire=questionnaires["generic"],
            is_non_standard_destination=is_non_std, has_attachments=total_att > 0, attachment_count=total_att,
            forward_to_email=CONFIG.non_standard_forward_email if is_non_std else None,
            forward_reason=f"non_standard:{country.code}" if is_non_std else None, confidence_score=conf,
        )
    
    def _empty(self, prev):
        p = LeadStatus.from_string(prev)
        return ThreadAnalysis(Language.RUSSIAN, None, Intent.OTHER, UrgencyLevel.NORMAL, Sentiment.NEUTRAL, p, p)


# ═══════════════════════════════════════════════════════════════════════════════
# ✉️ ГЕНЕРАТОР ОТВЕТОВ
# ═══════════════════════════════════════════════════════════════════════════════

class ReplyGenerator:
    def __init__(self, config=CONFIG, branding=AI_BRAND):
        self.config, self.branding = config, branding
    
    def generate(self, messages, analysis, q_links, extra_ctx=None, model=None, lead_id: Optional[Union[int, str]] = None):
        """
        Генерирует ответ. 
        lead_id используется для генерации ссылок.
        """
        b = self.branding
        is_en = analysis.language == Language.ENGLISH
        
        # Определяем, какую ссылку (или ссылки) нужно отправить
        target_urls = self._resolve_target_urls(analysis, q_links, lead_id)
        
        sys_prompt = f"""You are {b.agent_name} v{b.agent_version} - intelligent AI assistant at {b.company_name}.

{b.robot_emoji} STYLE: Write clear, professional, empathetic emails. Be helpful and proactive.

{b.check_emoji} RULES:
1. Answer directly and completely.
2. NEVER invent facts about consulates, prices, or timelines.
3. If urgent, acknowledge and commit to priority.
4. IMPORTANT: I will provide you with specific questionnaire links. You MUST include them naturally in your response.

{b.info_emoji} TERMINOLOGY: Use "ОПРОСНИК" (QUESTIONNAIRE), NOT "анкета" (form)!

{b.star_emoji} SIGNATURE (always include):
{b.line_thin}
{b.robot_emoji} {'This message was generated by' if is_en else 'Сообщение сформировано'} {b.agent_name} v{b.agent_version}
{b.sparkle_emoji} {'Intelligent Visa Processing System' if is_en else 'Интеллектуальная система обработки визовых заявок'}

{'Best regards' if is_en else 'С уважением'},
{b.company_name}
visa@bcdtravel.kz"""

        user_prompt = self._build_user_prompt(messages, analysis, target_urls, is_en)
        
        reply = generate_chat_completion([{"role": "system", "content": sys_prompt}, {"role": "user", "content": user_prompt}],
                                         model=model or self.config.default_model, max_tokens=self.config.max_tokens_reply, temperature=self.config.temperature)
        
        # 🔥 SAFETY NET: Если AI забыл ссылку, мы её добавим
        return self._postprocess(reply, analysis, target_urls)
    
    def _resolve_target_urls(self, analysis, q_links, lead_id) -> Dict[str, str]:
        """
        Определяет, какие ссылки должны быть в письме.
        Возвращает словарь {Название: URL}.
        """
        urls = {}
        if analysis.needs_questionnaire:
            if analysis.offer_poland_questionnaire and q_links.poland:
                urls["Poland"] = q_links.get_personal_link("poland", lead_id)
            if analysis.offer_schengen_questionnaire and q_links.schengen:
                urls["Schengen"] = q_links.get_personal_link("schengen", lead_id)
            if analysis.offer_usa_questionnaire and q_links.usa:
                urls["USA"] = q_links.get_personal_link("usa", lead_id)
            if analysis.offer_generic_questionnaire and q_links.generic:
                urls["Generic"] = q_links.get_personal_link("generic", lead_id)
        return urls
    
    def _build_user_prompt(self, messages, analysis, target_urls, is_en):
        b = self.branding
        parts = [f"{b.robot_emoji} ANALYSIS: Intent={analysis.intent.value}, Country={analysis.country_code or 'unknown'}, Urgency={analysis.urgency.emoji}{analysis.urgency.name}"]
        
        # --- ИЗМЕНЕНИЕ ЗДЕСЬ ---
        # Мы передаем ссылки, но меняем инструкцию
        if target_urls:
            url_list_str = "\n".join([f"- {k}: {v}" for k, v in target_urls.items()])
            parts.append(f"\n{b.form_emoji} POTENTIAL QUESTIONNAIRE LINKS (Use ONLY if relevant):\n{url_list_str}")
        
        conv = "\n---\n".join(f"From: {'BCD' if m.from_address.lower() == self.config.mailbox_upn.lower() else 'Client'}\n{m.get_clean_body()}" for m in messages)
        parts.append(f"\n📧 THREAD:\n{conv}")
        
        hints = []
        if analysis.is_urgent: hints.append(f"{b.urgent_emoji} URGENT - acknowledge urgency!")
        
        task = f"\n{b.robot_emoji} TASK: Write a professional reply."
        
        # --- ГЛАВНОЕ УЛУЧШЕНИЕ: УМНЫЙ ФИЛЬТР ---
        if target_urls:
            task += """
CRITICAL INSTRUCTION ABOUT LINKS:
1. I have provided potential questionnaire links above.
2. ANALYZE the user's intent carefully.
3. IF the user is asking a theoretical question (e.g., "Do I need a visa?", "Is UK part of Schengen?"), DO NOT include the link. Answer the question only.
4. IF the user expresses a desire to apply (e.g., "I want to go", "How to start", "Send me the form"), THEN include the link naturally.
5. IF the user explicitly said "I don't need a questionnaire", DO NOT include it.
6. If you decide to include the link, embed it naturally in the text.
"""
            
        if hints: task += "\n" + "\n".join(hints)
        parts.append(task)
        
        return "\n\n".join(parts)
    
    def _postprocess(self, reply, analysis, target_urls):
        b = self.branding
        
        # 1. Замена терминов
        if analysis.language != Language.ENGLISH:
            reply = re.sub(r'\bанкет[аыуеойи]?\b', 'опросник', reply, flags=re.IGNORECASE)
        
        # 2. 🔥 SAFETY NET: Проверяем, вставил ли AI ссылки
        # Если ссылка есть в target_urls, но её нет в тексте (reply), добавляем в блок P.S.
        missing_links = []
        for name, url in target_urls.items():
            if url and url not in reply:
                missing_links.append(f"{name}: {url}")
        
        if missing_links:
            # Аккуратно добавляем в конец, перед футером (если получится) или просто в конец
            safety_block = "\n\n" + (f"Link: " if len(missing_links) == 1 else "Links: ") + " ".join(missing_links)
            
            # Пытаемся вставить перед линией футера
            if b.line_thin in reply:
                reply = reply.replace(b.line_thin, safety_block + "\n" + b.line_thin, 1)
            else:
                reply += safety_block

        # 3. Футер
        if b.agent_name not in reply:
            reply += b.get_footer_en() if analysis.language == Language.ENGLISH else b.get_footer_ru()
        
        return reply.strip()


# ═══════════════════════════════════════════════════════════════════════════════
# 🚀 ПУБЛИЧНЫЕ API
# ═══════════════════════════════════════════════════════════════════════════════

def _normalize_messages(data):
    if isinstance(data, str): return [Message("", "", data)]
    return [Message.from_dict(i) if isinstance(i, dict) else (i if isinstance(i, Message) else Message("", "", str(i))) for i in data]

def classify_message(thread_messages, our_address=CONFIG.mailbox_upn, previous_status=None,
                    existing_poland_questionnaire=False, existing_schengen_questionnaire=False,
                    existing_usa_questionnaire=False, existing_generic_questionnaire=False) -> Dict[str, Any]:
    """🔍 Классификация сообщений"""
    msgs = _normalize_messages(thread_messages)
    existing = {"poland": existing_poland_questionnaire, "schengen": existing_schengen_questionnaire, "usa": existing_usa_questionnaire, "generic": existing_generic_questionnaire}
    return ThreadAnalyzer().analyze(msgs, our_address, previous_status, existing).to_dict()

def generate_reply_from_thread(thread_messages_or_text, our_address=CONFIG.mailbox_upn, previous_status=None,
                               existing_poland_questionnaire=False, existing_schengen_questionnaire=False,
                               existing_usa_questionnaire=False, existing_generic_questionnaire=False,
                               questionnaire_links=None, extra_config=None, model=None) -> str:
    """✉️ Генерация ответа с AI-брендингом"""
    msgs = _normalize_messages(thread_messages_or_text)
    existing = {"poland": existing_poland_questionnaire, "schengen": existing_schengen_questionnaire, "usa": existing_usa_questionnaire, "generic": existing_generic_questionnaire}
    analysis = ThreadAnalyzer().analyze(msgs, our_address, previous_status, existing)
    
    # Extract lead_id from extra_config if present
    lead_id = extra_config.get("lead_id") if extra_config else None
    
    return ReplyGenerator().generate(
        msgs, 
        analysis, 
        questionnaire_links or QuestionnaireLinks.from_config(), 
        extra_config, 
        model,
        lead_id=lead_id
    )

def analyze_single_message(text: str) -> Dict[str, Any]:
    """🧪 Быстрый анализ"""
    return classify_message(text)

def get_ai_branding() -> AIBranding:
    """🎨 Получить брендинг"""
    return AI_BRAND

def print_analysis_report(text: str):
    """📊 Красивый отчёт"""
    a = classify_message(text)
    print(f"""
╔══════════════════════════════════════════════════════════════════════════════╗
║ {AI_BRAND.robot_emoji} {AI_BRAND.agent_name} v{AI_BRAND.agent_version} — ОТЧЁТ АНАЛИЗА                              ║
╠══════════════════════════════════════════════════════════════════════════════╣
║ 🌐 Язык: {a['language']:<20} ║ 🎯 Намерение: {a['intent']:<15} ║
║ 🌍 Страна: {(a['country'] or 'не определена'):<18} ║ {a['urgency_emoji']} Срочность: {a['urgency_level']:<12} ║
╠══════════════════════════════════════════════════════════════════════════════╣
║ 📈 Статус: {a['previous_status']:<15} → {a['new_status']:<15}                    ║
║ 📋 Опросник: {'Да (' + a['questionnaire_type'] + ')' if a['needs_questionnaire'] else 'Нет':<20}                                   ║
║ ⚠️ Нестандартное: {'Да' if a['is_non_standard_destination'] else 'Нет':<5}       📊 Уверенность: {a['confidence_score']:.0%}                 ║
╚══════════════════════════════════════════════════════════════════════════════╝
""")


# ═══════════════════════════════════════════════════════════════════════════════
# 📦 ЭКСПОРТ
# ═══════════════════════════════════════════════════════════════════════════════

__all__ = [
    "Message", "QuestionnaireLinks", "ThreadAnalysis", "Country", "Config", "AIBranding",
    "Language", "Intent", "LeadStatus", "UrgencyLevel", "VisaCategory", "Sentiment",
    "ThreadAnalyzer", "ReplyGenerator", "CountryDatabase",
    "classify_message", "generate_reply_from_thread", "analyze_single_message", "get_ai_branding", "print_analysis_report",
    "CONFIG", "COUNTRY_DB", "AI_BRAND",
]

if __name__ == "__main__":
    test = "Здравствуйте! Хочу оформить визу в Германию для деловой поездки. Срочно, вылет через неделю. Какие документы нужны?"
    print_analysis_report(test)